# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkPractice1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'ObjectMapper', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.0'

  # Pods for NetworkPractice1

end
