# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'secondTodo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for secondTodo
  pod "GlitchLabel", "~> 2.0.0"
  pod "Twinkle", "~> 0.3.0"

  target 'secondTodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'secondTodoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
