# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TDDExample' do
  use_frameworks!
  
  # UI
  pod 'SnapKit',                '~> 4.0'

  # Network
  pod 'Alamofire',              '~> 4.7'
  pod 'AlamofireObjectMapper',  '~> 5.0'
  pod 'Moya',                   '~> 11.0'
  
  # Rx
  pod 'RxSwift',                '~> 4.0'
  pod 'RxCocoa',                '~> 4.0'
  pod 'Moya/RxSwift',           '~> 11.0'
  
  # Util
  pod 'ObjectMapper',           '~> 3.1'
  pod 'Then',                   '~> 2.3'

  target 'TDDExampleTests' do
    inherit! :search_paths
  end
end

