# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'OneBobYoung' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ObjectMapper', '~> 3.1'
  pod 'DOFavoriteButton', :git => 'https://github.com/fumiyasac/DOFavoriteButton'
  
  pod 'RealmSwift'
  
  pod 'TisprCardStack', '~> 2.0'
  pod 'CRToast', '~> 0.0.7'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  
  # Pods for OneBobYoung

end
